DHDomtica/ViewModels/Admin/AdminManageProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using DHDomtica.Models;
using DHDomtica.Supportclasses;
using System.Collections;

namespace DHDomtica.ViewModels
{
    public class AdminManageProductViewModel
    {
        public int ID { get; set; }

        [DataType(DataType.Text)]
        [DisplayName("Productnaam")]
        [Required(ErrorMessage = "Vul een productnaam in")]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        [DisplayName("Productbeschrijving")]
        [Required(ErrorMessage = "Vul een productbeschrijving in in")]
        public string Description { get; set; }

        [DataType(DataType.Text)]
        [DisplayName("Productprijs")]
        [Required(ErrorMessage = "Vul een productprijs in")]
        [RegularExpression(@"^(\d+(?:[\.\,]\d{1,2})?)$", ErrorMessage = "Vul een correcte prijs in met punt en 2 cijfers achter de punt, zoals 123.45")]
        public double Price { get; set; }

        [DataType(DataType.Text)]
        [DisplayName("Productvoorraad")]
        [Required(ErrorMessage = "Vul een productvoorraad in")]
        public int Stock { get; set; }

        [DataType(DataType.ImageUrl)]
        [DisplayName("Productafbeelding")]
        [Required(ErrorMessage = "Vul een URL voor het plaatje van Uw product in")]
        [RegularExpression(@"^https?:\/\/(?:[a-z\-]+\.)+[a-z]{2,6}(?:\/[^\/#?]+)+\.(?:jpe?g|gif|png)$", ErrorMessage = "Vul een correcte URL van de afbeelding in, zoals 'https://www.hashop.nl/Files/5/18000/18005/ProductPhotos/360x200/222127103.png'")]
        public string Image { get; set; }

        [DisplayName("Productcategorie")]
        [Required(ErrorMessage = "Vul een categorienummer van uw product in")]
        public int MainCategoryID { get; set; }

        [DisplayName("Productcategorie")]
        public virtual MainCategory MainCategory { get; set; }

        public AdminManageProductViewModel()
        {

        }

        internal void CreateNewProduct()
        {
            Product product = new Product()
            {
                Name = Name,
                Description = Description,
                Price = Price,
                Stock = Stock,
                Image = Image,
                MainCategoryID = MainCategoryID
            };

            using (DHDomoticaDBEntities DHDomoticadbModel = new DHDomoticaDBEntities())
            {
                DHDomoticadbModel.Products.Add(product);
                DHDomoticadbModel.SaveChanges();
            }
        }

        internal void ChangeExistingProduct(int ID)
        {
            // Iets met int ID = 0 toevoegen, zodat controller weet welk product hij moet pakken.
            using (DHDomoticaDBEntities DHDomoticadbModel = new DHDomoticaDBEntities())
            {
                Product product = DHDomoticadbModel.Products.FirstOrDefault(x => x.ID == ID);
                {
                    product.Name = Name;
                    product.Description = Description;
                    product.Price = Price;
                    product.Stock = Stock;
                    product.Image = Image;
                    product.MainCategoryID = MainCategoryID;
                    // Ik weet niet of de foreign key hiervan goed is
                };
                {
                    DHDomoticadbModel.SaveChanges();
                }
            }
        }

        public AdminManageProductViewModel(Product product)
        {
            Name = product.Name;
            ID = product.ID;
            Description = product.Description;
            Price = product.Price;
            Stock = product.Stock;
            Image = product.Image;
            MainCategoryID = product.MainCategoryID;
        }

        public IEnumerable<AdminManageProductViewModel> VMList()
        {
            var vmProduct = new List<AdminManageProductViewModel>();
            using (DHDomoticaDBEntities DHDomoticadbModel = new DHDomoticaDBEntities())
            {
                var product = DHDomoticadbModel.Products;
                foreach (Product i in product)
                {
                    var test = new AdminManageProductViewModel(i);
                    vmProduct.Add(test);
                }
            }
            IEnumerable<AdminManageProductViewModel> enumerator = vmProduct.AsEnumerable<AdminManageProductViewModel>();
            return enumerator;
        }
    }
}

DHDomtica/Controllers/Admin/AdminManageProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DHDomtica.Models;
using DHDomtica.ViewModels;
using DHDomtica.Supportclasses;
using System.Data.Entity.Infrastructure;

namespace DHDomtica.Controllers
{
    public class AdminManageProductsController : Controller
    {
        private DHDomoticaDBEntities db = new DHDomoticaDBEntities();

        // GET: Products
        public ActionResult Index(string searchString)
        {
            var product = new AdminManageProductViewModel().VMList();
            if (!string.IsNullOrEmpty(searchString))
            {
                product = product.Where(p => p.Name.Contains(searchString));
                
            }
            ShowAdminSidebar();
            
            return View(product);

        }
        //Code for the AdminsideBar
        private void ShowAdminSidebar()
        {
            System.Diagnostics.Debug.WriteLine($"AdminSidebar {Request.RawUrl}");
            ViewBag.ShowAdminSideBar = true;
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ShowAdminSidebar();
            var adminProductModelEnum = new AdminManageProductViewModel(product);
            return View(adminProductModelEnum);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.MainCategoryID = new SelectList(db.MainCategories, "ID", "Name");
            ShowAdminSidebar();
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,Price,Stock,Image,MainCategoryID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                ShowAdminSidebar();
                return RedirectToAction("Index");
            }
            else
            {
                ShowAdminSidebar();
                ViewBag.MainCategoryID = new SelectList(db.MainCategories, "ID", "Name", product.MainCategoryID);
                return View("Create", product);
            }
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            //ViewBag.MainCategoryID = new SelectList(db.MainCategories, "ID", "Name", product.MainCategoryID);

            var adminProductModelEnum = new AdminManageProductViewModel(product);
            ShowAdminSidebar();
            return View(adminProductModelEnum);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,Price,Stock,Image,MainCategoryID")] Product product)
        {
            if (!ModelState.IsValid)
            {
                ShowAdminSidebar();
                ViewBag.MainCategoryID = new SelectList(db.MainCategories, "ID", "Name", product.MainCategoryID);
                return View("Edit", product);
            }
            else
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                ShowAdminSidebar();
                return RedirectToAction("Index");
            }
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ShowAdminSidebar();
            var adminProductModelEnum = new AdminManageProductViewModel(product);
            return View(adminProductModelEnum);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            var wl = db.Wishlists.Where(l => l.ProductID.Equals(id));
            db.Wishlists.RemoveRange(wl);
            db.Products.Remove(product);
            db.SaveChanges();
            ShowAdminSidebar();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DHDomtica/Views/AdminManageProducts/Create.cshtml
@model DHDomtica.ViewModels.AdminManageProductViewModel

<!DOCTYPE html>

@*TODO: This DropDownlist needs to be managed through the Database instead of being hardcoded - This is only a temporary solution!!!*@
@{
    List<SelectListItem> MainCategoryDropDown = new List<SelectListItem>();
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Smart Home",
        Value = "1"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Cameras",
        Value = "2"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Controller",
        Value = "3"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Modules",
        Value = "4"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Sensoren",
        Value = "5"
    });
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Product aanmaken</title>
</head>
<body>
    @using (Html.BeginForm("Create", "AdminManageProducts", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MainCategoryID, "Productcategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => Model.MainCategoryID, MainCategoryDropDown, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MainCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Product aanmaken" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Terug naar productenlijst", "Index")
    </div>
</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DHDomtica/Views/AdminManageProducts/Delete.cshtml
@model DHDomtica.ViewModels.AdminManageProductViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Product verwijderen</title>
</head>
<body>
    <h3>Weet u zeker dat u dit product wilt verwijderen?</h3>
    <div>
        <h4>Product</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Stock)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Stock)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Image)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Image)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MainCategoryID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MainCategoryID)
            </dd>

            @*<dt>
            @Html.DisplayNameFor(model => model.MainCategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MainCategory.Name)
        </dd>*@

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Verwijder product" class="btn btn-default" /> |
                @Html.ActionLink("Terug naar productenlijst", "Index")
            </div>
        }
    </div>
</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DHDomtica/Views/AdminManageProducts/Details.cshtml
@model DHDomtica.ViewModels.AdminManageProductViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Productdetails</title>
</head>
<body>
    <div>
        <h4>Product</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Stock)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Stock)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Image)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Image)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MainCategoryID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MainCategoryID)
            </dd>

            @*<dt>
            @Html.DisplayNameFor(model => model.MainCategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MainCategory.Name)
        </dd>*@

        </dl>
    </div>
    <p>
        @Html.ActionLink("Product aanpassen", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Terug naar productenlijst", "Index")
    </p>
</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DHDomtica/Views/AdminManageProducts/Edit.cshtml
@model DHDomtica.ViewModels.AdminManageProductViewModel

<!DOCTYPE html>


@*TODO: This DropDownlist needs to be managed through the Database instead of being hardcoded - This is only a temporary solution!!!*@
@{
    List<SelectListItem> MainCategoryDropDown = new List<SelectListItem>();
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Smart Home",
        Value = "1"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Cameras",
        Value = "2"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Controller",
        Value = "3"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Modules",
        Value = "4"
    });
    MainCategoryDropDown.Add(new SelectListItem
    {
        Text = "Sensoren",
        Value = "5"
    });
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Product aanpassen</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MainCategoryID, "Productcategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => Model.MainCategoryID, MainCategoryDropDown, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MainCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Veranderingen opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Terug naar productenlijst", "Index")
    </div>
</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DHDomtica/Views/AdminManageProducts/Index.cshtml
@model IEnumerable <DHDomtica.ViewModels.AdminManageProductViewModel>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Productenlijst</title>
</head>
<body>
    <p>
        @Html.ActionLink("Voeg een nieuw product toe", "Create")
    </p>
    @using (Html.BeginForm("Index", "AdminManageProducts"))
    { 
        <input class="form-control" name="searchString" type="Search" placeholder="Zoeken" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
        <i class="fas fa-search"></i>
    </button>
    }
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MainCategoryID)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.Stock)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MainCategoryID)
            </td>
            <td>
                @Html.ActionLink("Aanpassen", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Verwijderen", "Delete", new { id = item.ID })
            </td>
        </tr>
        }

    </table>
</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}